name: Test Suite

on:
  push:
    branches:
      - main

jobs:
    test_python_3.10:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s test -p "*test*.py"

    test_python_3.11:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s test -p "*test*.py"

  test_with_orjson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies with orjson
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with orjson
        run: |
          python -m unittest discover -s test -p "*test*.py"

  test_without_orjson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies without orjson
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y orjson  # Remove orjson if present
          pip install -r requirements.txt

      - name: Run tests without orjson
        run: |
          python -m unittest discover -s test -p "*test*.py"
