name: Run Tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        orjson: [true, false]
    env:
      MODE: "dev"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyyaml

          if my test file requier a module is insid the root but i run test like 
