name: Run Tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        orjson: [true, false]
    env:
      MODE: "dev"
    steps:
      - uses: actions/checkout@v2

      - name: Debug Directory
        run: |
          ls -R

      - name: Setup Python 
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r testing/requirements.txt
          pip install pyyaml

      - name: Set Python Path
        run: |
          export PYTHONPATH=$PYTHONPATH:/path/to/simulation

      - name: Run Tests
        run: |
          python ./testing/test/test_model.py
          python ./testing/test/test_minimal_paths.py
