name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        orjson: [false, true]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if ${{ matrix.orjson }}; then pip install orjson; fi

      - name: Run tests
        run: |
          pytest
          if ${{ matrix.orjson }}; then pytest --with-orjson; fi

