name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your project's requirements here
          pip install pytest              # Install pytest
      
      - name: Run tests without orjson
        run: pytest testing/test/test_minimal_paths.py testing/test/test_model.py

      - name: Install orjson and rerun tests
        run: |
          pip install orjson
          pytest testing/test/test_minimal_paths.py testing/test/test_model.py
      - name: Clean up
        run: |
          pip uninstall -y orjson
